spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create


  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: '{cipher}6890e982e21dd2420c0bda1a650ff5ee9b637a205c56295c0e0b3213830e247e'

server:
  port: 8084

yoke:
  notify:
    url: http://localhost:8082/event
