spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: '{cipher}AgCU61Jia0hpGhenRkXy1w7i1oL22++DjX50U9hUfq1/KZthVmZNY0oS2G8ahkYqO0qxvJE4XVE6GJF7eCnBPk1E7vaYfYYCzTmlZ4T3/OO9V/FoZkGIwEsRCnMr7FETolhQlgaEysroFfnoW3iH5yVfVccVPu6DFuoc6VM1xiuuiKC6HVwZRKnTfQNCNgRspvt+KC8GY7UQB6ckInB/YiRbd1Bvcml7WQLLGV/D9ujSlZuW4A7FJVvWk1C3aAyi/+TB4F4z8JjmhWaIlQc6111N9bC5073p02ZaBGNz8FTtYZRGP30V5OFFHc6Vkqqz7P9SgHC6rgsYjwNz3NH7y0qaONzLubMyZhHGulibksRajpVnNXXCPukco7vm42iKRZ9n0zvHtYHtXmHIFLWQPxu305PTiVbCAwXlam901k5DNFCuoCA2fgvaITerFyesaOltpOdOCe1DyUyKG7PaTQmlEER0UdqxJByPBi3Kx8QPFXEM/bNuTDnPSki8+EJKAfA9qme6UEM3ILe7uXEGqshRw5VzrSiCqsYH6SSm4niKqm+8XRuhOjs/9tCsuPif8G4CIWzT+JzB4wOf3JRjV/stGLbEDTPZAeFiIweqS1GGPO2rLQQYOaos5aAN6nRMSEwO2//wMnzb9Err2rKYsOWMPFxI0A0LGbvLtg6m+3XvGA3xP4uplDPX4ghnV5mhOuCrXfZmNddUvtV2CnUnTbOA'

yoke:
  notify:
    url: http://localhost:8082/event
