spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create


  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: {cipher}e4f75ba25a964ff0d52c53f5fab13798cff90960da291b5766caf42ef36146a4

server:
  port: 8084

yoke:
  notify:
    url: http://localhost:8082/event
